In [1]:
import numpy as np  
import random  
            
b1 = np.zeros((8, 8))
b2 = np.zeros((8, 8))
b3 = np.zeros((8, 8))
b4 = np.zeros((8, 8))
print("INITIAL POPULATION")
print(b1,
      b2,
      b3,
      b4)
for i in range(8):
    col_no1=np.random.randint(0,8)
    b1[i][col_no1]=1
    
    col_no2=np.random.randint(0,8)
    b2[i][col_no2]=1
   
    col_no3=np.random.randint(0,8)
    b3[i][col_no3]=1
    
    col_no4=np.random.randint(0,8)
    b4[i][col_no4]=1
def verticalupper(b,x,y):
    while(x>0):  
        x=x-1
        if b[x][y]==1:
            return True;
    return False;
def verticallower(b,x,y):
       while(x<7):  
        x=x+1
        if b[x][y]==1:
            return True;
    
       return False;
#checking lowerright diagnol
def lowerright(b,x,y):
    while(x<7 and y<7):
        x=x+1
        y=y+1 
        if b[x][y]==1:
            return True;     
        
    return False;
#checking lowerleft diagnol
def lowerleft(b,x,y):
    while(x<7 and y>0):
        x=x+1
        y=y-1 
        if b[x][y]==1:
            return True;
        
    return False;
#checking upperright diagnol           
def upperright(b,x,y):
    while(x>0 and y<7):
        x=x-1
        y=y+1 
        if b[x][y]==1:
            return True;    
        
    return False;
#checking upperleft diagnol
def upperleft(b,x,y):
    while(x>0 and y>0):
        x=x-1
        y=y-1 
        if b[x][y]==1:
            return True;
        
    return False;
def checkbadness(b):
    f=0
    for i in range(8):
        for j in range(8):
            if b[i][j]==1:
                if (verticalupper(b,i,j) or verticallower(b,i,j) or lowerright(b,i,j) or lowerleft(b,i,j) or upperright(b,i,j) or upperleft(b,i,j)): 
                    f=f+1
                    
    return f;

def rowslist(a):
    i=0
    j=0
    rowlist=[]
    for i in range(8):
        for j in range(8):
            if a[i][j]==1:
                rowlist.append(j)
    return rowlist;

def crossover(a,b):
    temp=[]
    for i in range(8):
        if i<4:
            temp.append(a[i])
        else:
            temp.append(b[i])
    print("CROSSOVERED CHILD IS: " ,temp)        
    return temp;    
           
def mutation(a):
    while(1):
        rand=np.random.randint(0,8)
        rand2=np.random.randint(0,8)
        if rand2!=a[rand]:
            a[rand]=rand2
            break;
        if rand2==a[rand]:
            rand2=np.random.randint(0,8)
            a[rand]=rand2
            break;
    print("TOGGLED CHILD IS: ", a)
    return a;  

def generatenewpopulation(cb):
    child = np.zeros((8, 8))
    for i in range(8):
        child[i][cb[i]]=1
            
    #print(child)
    return child;
    
    
    
def selectnewpopulation(b1,b2,b3,b4):
    #d=dict()
    pop=dict()
    d=[b1,b2,b3,b4]
    c1=checkbadness(b1)
    c2=checkbadness(b2)
    c3=checkbadness(b3)
    c4=checkbadness(b4)
    #print(b1)
    print("BADNESS OF BOARD NO 1: " ,c1)
    #print(b2)
    print("BADNESS OF BOARD NO 2: "  ,c2)
    #print(b3)
    print("BADNESS OF BOARD NO 3: " ,c3)
    #print(b4)
    print("BADNESS OF BOARD NO 4: " ,c4)
    badness=np.array([c1,c2,c3,c4])
    badness=sorted(badness)
    print(badness)
    h=min(badness)    
    #print(h)
    flag1=False
    flag2=False
    flag3=False
    flag4=False
    if h==c1:
        r1=rowslist(b1)
        flag1=True
    elif h==c2:
        r1=rowslist(b2)
        flag2=True
    elif h==c3:
        r1=rowslist(b3) 
        flag3=True
    elif h==c4:
        r1=rowslist(b4)
        flag4=True
    #print(flag1)  
    #print(flag2)
    #print(flag3)  
    #print(flag4)
    badness.remove(h)
    badness=sorted(badness)
    print(badness)
    h2=min(badness) 
    if h2==c1 and flag1==False:
        r2=rowslist(b1)  
    if h2==c2 and flag2==False:
        r2=rowslist(b2)
    if h2==c3 and flag3==False:
        r2=rowslist(b3)    
    if  h2==c4 and flag4==False:
        r2=rowslist(b4)
          
    
    child1=crossover(r1,r2)   
    child2=crossover(r2,r1)
    child1=mutation(child1) 
    child2=mutation(child2)
    newboard1=generatenewpopulation(r1)
    newboard2=generatenewpopulation(r2)
    newboard3=generatenewpopulation(child1)
    newboard4=generatenewpopulation(child2)
    #print("NEW BOARDS")
    #print(r1,r2,child1,child2)
    print("BADNESS OF BOARD NO 1: " ,checkbadness(newboard1))
    #print(b2)
    print("BADNESS OF BOARD NO 2: "  ,checkbadness(newboard2))
    #print(b3)
    print("BADNESS OF BOARD NO 3: " ,checkbadness(newboard3))
    #print(b4)
    print("BADNESS OF BOARD NO 4: " ,checkbadness(newboard4))
    return newboard1,newboard2,newboard3,newboard4;
   
c1=selectnewpopulation(b1,b2,b3,b4)  
count=0

while True:
    if checkbadness(c1[0])==0:
        print("IN ",count,"ITERATIONS")
        print(c1[0])
        print(checkbadness(c1[0]))
        break
    if checkbadness(c1[1])==0:
        print("IN ",count,"ITERATIONS")
        print(c1[1])
        print(checkbadness(c1[1]))
        break
    if checkbadness(c1[2])==0:
        print("IN ",count,"ITERATIONS")
        print(c1[2])
        print(checkbadness(c1[2]))
        break
    if checkbadness(c1[3])==0:
        print("IN ",count,"ITERATIONS")
        print(c1[3])  
        print(checkbadness(c1[3]))
        break
    if count>5000:
        print("TIME OUT ")  
        print("counter is",count)
        print(min(checkbadness(c1[0]),checkbadness(c1[1]),checkbadness(c1[2]),checkbadness(c1[3])))
        #print(checkbadness(c1[0]))
        break
    else:
        count=count+1
        c1=selectnewpopulation(c1[0],c1[1],c1[2],c1[3])
   
        
#generatenewpopulation(b1,b2,b3,b4)


INITIAL POPULATION
[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]] [[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]] [[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]] [[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]
BADNESS OF BOARD NO 1:  7
BADNESS OF BOARD NO 2:  7
BADNESS OF BOARD NO 3:  6
BADNESS OF BOARD NO 4:  8
[6, 7, 7,