# Assignment 1 
# Bcsf19a526 
# IRS

Information retrieval is the process of obtaining information system resources that are relevant to an information need from a collection of those resources. The core purpose of this assignment is to give you the flavor of IRS. You need to follow some steps listed below and in the end, you'll be able to build your own small IRS. So, let's start.

In [36]:
# required imports
import numpy as np
import fnmatch
import os


Suppose we have 3 files containing data :

### File Contents

<img src="1.png"/>
<img src="2.png"/>
<img src="3.png"/>

# Step 1 Create Files with Dummy data

You have to create few files with dummy data of your own choice as shown above.

# Step 2 Traverse Directories

 Now, You have to traverse the directories and store all the files into a dict type variable(files_dict). 

In [37]:
# Here we have intialized some variables, you can add more if required.

file_count = 0             # file_count to count number of files
files_dict = {}            # files_dic to store count of every file    
unique_word_set = set()    # unique_word_set to store all the unique words in a set


In [38]:
#Your code starts here   
import os
import numpy as np
# folder path
dir_path ='C:\z\dummy'
count= 0
i=0
y=0
s=0
files_dict=dict()
filecontents={}
checkfile={}
uws=set()

os.chdir('C:\z\dummy')
for dir, subdir, file in os.walk('C:\z\dummy'):
     for f in file:
        count += 1
        
files_dict=dict() 
for dir, subdir, file in os.walk('C:\z\dummy'):
    for f in file:
        files_dict[f]=s
        s=s+1
#Your code ends here       

Displaying the count of files.

In [39]:
print("\nTotal Number  of files\n", count)


Total Number  of files
 3


Displaying Dictionary containing all files.

In [40]:
print("\nDictionary containing  files\n", files_dict)


Dictionary containing  files
 {'f1.txt': 0, 'f2.txt': 1, 'f3.txt': 2}


# Step 3 Extract Unique Vocabulary

In [41]:
# write code to print all the unique words in every file and store them in a set

In [42]:
#Your code starts here    
for dir, subdir, file in os.walk('C:\z\dummy'):
    for f in file: 
        inputfile=open(f,'r')
        filecontents=inputfile.read() 
        inputfile.close()
        filecontents=filecontents.lower()
        filecontents=filecontents.split()
        for word in filecontents:
            word=word.lower()
            uws.add(word)
            
            #unique_word_set=set(filecontents.split(" "))

print("Unique words in files")   
print(uws)  
print("Count of files",count) 
#Your code ends here

Unique words in files
{'pen', 'this', 'book', 'my', 'is', 'intresting'}
Count of files 3


### Expected Output

<img src="4.png"/>

# Step 4 Create Term Document Matrix

Create Term-Doc-matrix using Bag of word approach.and display its contents initially and finally.

In [43]:
# Create Term doc matrix such that colmns will be unique words and all the files will be rows
# Write code to count all the unique words appearances in all the files and store it in a dictionary for words 

In [44]:
#Your code starts here  
y=0;
s=0
x=len(uws)
res=dict()
tdm=np.zeros((count,x))
print(tdm)
for i in uws:
    res = dict.fromkeys(uws,0)
for i in uws:
    res[i]=y
    y=y+1
    
filesdict=dict() 
for dir, subdir, file in os.walk('C:\z\dummy'):
    for f in file:
        filesdict[f]=s
        s=s+1
        
print("dictionary of unique words:") 
print(res)
print("dictionary of files:")
print(filesdict)
#Your code ends here

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
dictionary of unique words:
{'pen': 0, 'this': 1, 'book': 2, 'my': 3, 'is': 4, 'intresting': 5}
dictionary of files:
{'f1.txt': 0, 'f2.txt': 1, 'f3.txt': 2}


### Expected Output

<img src="5.png"/>

# Step 5 Fill Term Document Matrix

In [45]:
# Fill the term doc matrix by checking if the unique word exists in a file or not
# If it exists then substitute a 1 in term_doc_matrix (eg : TERM_DOC_MATRIX[file][word] = 1 ) 
# Do the same for all the files present in the directory

In [46]:
#Your code starts here    
for dir, subdir, file in os.walk('C:\z\dummy'):
     for f in file:
        for words in uws:
            rf=open(f,'r')
            checkfile=rf.read()
            checkfile=checkfile.lower()
            checkfile=checkfile.split()
           
            if words in checkfile:
                tdm[filesdict[f]][res[words]]=1

print(tdm)

#Your code ends here

[[0. 1. 1. 1. 1. 0.]
 [1. 1. 0. 1. 1. 0.]
 [0. 0. 1. 1. 1. 1.]]


### Expected Output

<img src="6.png"/>

# Step 6 Ask for a user Query

In [47]:
# For user query make a column vector of length of all the unique words present in a set

In [48]:
#Your code starts here    
column_vector=np.zeros((1,len(uws)))
column_vector=column_vector.T
print(column_vector)
#Your code ends here

[[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]]


### Expected Output

<img src="7.png"/>

In [49]:
# Check every word of query if it exists in the set of unique words or not
# If exixts then increment the count of that word in word dictionary
query = input("\nWrite something for searching  ")


Write something for searching  this book is intresting


In [50]:
#Your code starts here 
for x in query.split(" "):
    if x in uws: 
        for i in res:
             if (x==i):
                column_vector[res[i],0]=column_vector[res[i],0]+1
    
print(column_vector)
#Your code ends here

[[0.]
 [1.]
 [1.]
 [0.]
 [1.]
 [1.]]


### Expected Output

<img src="8.png"/>

# Step 7 Display Resultant Vector

Display 
1. Resultant vector.
2. Max value in resultant vector.
3. Index of max value in resultant vector.


In [51]:
#Your code starts here  
resultant_vector=tdm.dot(column_vector)
print(resultant_vector)
print(type(resultant_vector))
#Your code ends here

[[3.]
 [2.]
 [3.]]
<class 'numpy.ndarray'>


### Expected Output

<img src="9.png"/>

# Step 8 Display the contents of file


In [52]:
#Write the code to identify the file_name having maximum value in the resultant vector and display its contents.

In [53]:
#Your code starts here    
max_value=np.max(resultant_vector)

z=0
for find in resultant_vector:
    if find==max_value:
        k=z
        break
    z=z+1

for key in filesdict:
    if filesdict[key]==k:
        #print(key)
        output=open(key,'r')
        contents=output.read()
        
        
print("Resultant Vector is:")
print(resultant_vector)
print("Maximum Value",max_value)
print("Index of maximum in resultant is:", k)
print("Contents of file:    ",contents)
#Your code ends here

Resultant Vector is:
[[3.]
 [2.]
 [3.]]
Maximum Value 3.0
Index of maximum in resultant is: 0
Contents of file:     This is my book


Congratulations Now you are able to build your own small IRS.